apiVersion: 1

datasources:
  - name: TimescaleDB
    uid: timescaledb
    type: grafana-postgresql-datasource
    url: timescaledb:5432
    user: grafana
    secureJsonData:
      password: $GRAFANA_DB_PASSWORD
    jsonData:
      database: $DB_NAME
      sslmode: disable
      postgresVersion: 1700
      timescaledb: true
    isDefault: true
    editable: false
